# what we're counting/aggregating (y-axis)
measure: animal

contextual_filters:
- for_organization

filters:
- key: created_at
  criteria:
    operator: between
    value: -90d - now

# columns/associations we're grouping by (x-axis)
dimensions:
- cohort
