# what we're counting/aggregating (y-axis)
measure: animal

# contextual_filters:
# - for_organization

# -- in model
# include ReportsKit::Model
# reports_kit do
#   contextual_filter :for_organization, ->(relation, context_params) do
#     relation.where(organization_id: context_params[:organization_id])
#   end
# end
# -- in report
# <%= render_report 'my_report', context_params: { organization_id: current_user.organization_id }

# filters:
# - key: organization.id
#   criteria:
#     value: <%= current_user&.organization&.id %>

    # columns/associations we're grouping by (x-axis)
dimensions:
- date_time_collected
